# Common Labels
labels:
  app: "case"
  group: "backend"

# Ingress Configs
ingress:
  zuul: true
  enabled: true
  context: "case"


# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "case_service_schema"
    image:
      repository: "pucarsolutionsdev.azurecr.io/case_db"
      tag: v1.0.0-66cf9764c39721c25d36ee62799cec6953427d9e

# Container Configs
image:
  repository: "pucarsolutionsdev.azurecr.io/pucar_case"
  tag: v1.0.0-66cf9764c39721c25d36ee62799cec6953427d9e
  imagePullPolicy: Always
replicas: "1"
httpPort: 8080
appType: "java-spring"
heap: "-Xmx1536m -Xms1536m -agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n"
debugPort: 8000
remote_debug:
  enabled: true
java-args: "-Dspring.profiles.active=monitoring"
memory_requests: 2Gi
memory_limits: 2Gi

healthChecks:
  enabled: true
  livenessProbePath: "/case/health"
  readinessProbePath: "/case/health"

env: |
  - name: NOTIFICATION_SMS_ENABLED
    value: "false"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: EGOV_DRISTI_CASE_PDF_HOST
    valueFrom:
      configMapKeyRef:
        key: dristi-case-pdf
        name: egov-service-host
  - name: SPRING_FLYWAY_URL
    valueFrom:
      configMapKeyRef:
        key: db-url
        name: egov-config
  - name: SPRING_FLYWAY_USER
    valueFrom:
      secretKeyRef:
        key: username
        name: db
  - name: SPRING_FLYWAY_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-url
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: "SCHEMA_TABLE"
    value: "case_service_schema"
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_HRMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-hrms
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: /egov-mdms-service/v1/_search
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_LOCALIZATION_SEARCH_ENDPOINT
    value: /localization/messages/v1/_search
  - name: SERVER_PORT
    value: "8080"
  - name: SERVER_CONTEXT_PATH
    value: /case
  - name: EGOV_IDGEN_PATH
    value: "egov-idgen/id/_generate"
  - name: EGOV_INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        key: individual
        name: egov-service-host
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        key: kafka-brokers
        name: egov-config
  - name: STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: EGOV_URL_SHORTNER
    valueFrom:
      configMapKeyRef:
        key: egov-url-shortening
        name: egov-service-host
  - name: EGOV_FILESTORE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
  - name: EGOV_ADVOCATE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: advocate
  - name: EGOV_BILLING_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: billing-service
  - name: KAFKA_TOPICS_RECEIPT_CREATE
    value: egov.collection.payment-create
  - name: PUCAR_LOCK_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: lock-service
  - name: EGOV_ENC_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-enc-service
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: case
  - name: SPRING_REDIS_HOST
    value: "redis.backbone"
  - name: SPRING_REDIS_PORT
    value: "6379"
  - name: EGOV_ENC_MDMS_SECURITY_POLICY_CASE_DECRYPT_SELF
    value: CaseDecryptSelfNew
  - name: EGOV_ENC_MDMS_SECURITY_POLICY_COURT_CASE
    value: CourtCaseNew
  - name: EGOV_ENC_MDMS_SECURITY_POLICY_CASE_DECRYPT_SELF_NEW
    value: CaseDecryptSelfNew
  - name: EGOV_ENC_MDMS_SECURITY_POLICY_COURT_CASE_NEW
    value: CourtCaseNew
  - name: EGOV_TASK_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: task
  - name: EGOV_HEARING_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: hearing
  - name: EGOV_EVIDENCE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: evidence
  - name: EGOV_PAYMENT_CALCULATOR_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: payment-calculator
  - name: EGOV_ETREASURY_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: etreasury
  - name: EGOV_SMS_NOTIFICATION_CASE_JUDGE_REGISTER_TEMPLATE_ID
    value: "1107174288665718004"