# Common Labels
labels:
  app: "hearing"
  group: "backend"

# Ingress Configs
ingress:
  zuul: true
  enabled: true
  context: "hearing"


# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "hearing_service_schema"
    image:
      repository: "pucarsolutionsdev.azurecr.io/pucar_hearing_db"
      tag: v1.0.0-08ab38363f9c4b0b70d0763331c9773f8bbf9820

# Container Configs
image:
  repository: "pucarsolutionsdev.azurecr.io/pucar_hearing"
  tag: v1.0.0-08ab38363f9c4b0b70d0763331c9773f8bbf9820
replicas: "1"
httpPort: 8080
appType: "java-spring"
heap: "-Xmx256m -Xms256m"
java-args: "-Dspring.profiles.active=monitoring"

healthChecks:
  enabled: true
  livenessProbePath: "/hearing/health"
  readinessProbePath: "/hearing/health"

env: |
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  - name: JAVA_DEBUG_PORT
    value: "5005"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: SPRING_FLYWAY_URL
    valueFrom:
      configMapKeyRef:
        key: db-url
        name: egov-config
  - name: SPRING_FLYWAY_USER
    valueFrom:
      secretKeyRef:
        key: username
        name: db
  - name: SPRING_FLYWAY_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-url
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: "SCHEMA_TABLE"
    value: "hearing_service_schema"
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: EGOV_HRMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-hrms
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_LOCALIZATION_SEARCH_ENDPOINT
    value: /_search
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: /egov-mdms-service/v1/_search
  - name: SERVER_PORT
    value: "8080"
  - name: SERVER_CONTEXT_PATH
    value: /hearing
  - name: EGOV_IDGEN_PATH
    value: "egov-idgen/id/_generate"
  - name: EGOV_BULK_INDEX_PATH
    value: "_bulk?refresh=true"
  - name: EGOV_INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        key: individual
        name: egov-service-host
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        key: kafka-brokers
        name: egov-config
  - name: EGOV_URL_SHORTNER
    valueFrom:
      configMapKeyRef:
        key: egov-url-shortening
        name: egov-service-host
  - name: EGOV_CASE_HOST
    valueFrom:
      configMapKeyRef:
        key: case
        name: egov-service-host
  - name: EGOV_APPLICATION_HOST
    valueFrom:
      configMapKeyRef:
        key: application
        name: egov-service-host
  - name: EGOV_PDF_HOST
    valueFrom:
      configMapKeyRef:
        key: pdf-service
        name: egov-service-host
  - name: EGOV_FILESTORE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-filestore
  - name: DRISTI_SCHEDULER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: scheduler
  - name: SPRING_DATASOURCE_WRITER_URL
    valueFrom:
      configMapKeyRef:
        key: db-url
        name: egov-config
  - name: SPRING_DATASOURCE_READER_URL
    valueFrom:
      configMapKeyRef:
        key: db-url
        name: egov-config
  - name: SPRING_DATASOURCE_WRITER_USERNAME
    valueFrom:
      secretKeyRef:
        key: writeusername
        name: db
  - name: SPRING_DATASOURCE_READER_USERNAME
    valueFrom:
      secretKeyRef:
        key: readusername
        name: db
  - name: SPRING_DATASOURCE_WRITER_PASSWORD
    valueFrom:
      secretKeyRef:
        key: writepassword
        name: db
  - name: SPRING_DATASOURCE_READER_PASSWORD
    valueFrom:
      secretKeyRef:
        key: readpassword
        name: db
  - name: MANAGEMENT_HEALTH_JDBC_ENABLED
    value: "false"
  - name: MANAGEMENT_HEALTH_REDIS_ENABLED
    value: "false"
  - name: EGOV_INFRA_INDEXER_HOST
    valueFrom:
      configMapKeyRef:
        key: es-indexer-host
        name: egov-config
  - name: EGOV_INBOX_HOST
    valueFrom:
      configMapKeyRef:
        key: inbox
        name: egov-service-host
  - name: DRISTI_TASK_HOST
    valueFrom:
      configMapKeyRef:
        key: task
        name: egov-service-host
  - name: EGOV_BILLINGSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        key: billing-service
        name: egov-service-host
  - name: DRISTI_ORDER_HOST
    valueFrom:
      configMapKeyRef:
        key: order
        name: egov-service-host
  - name: DRISTI_ANALYTICS_HOST
    valueFrom:
      configMapKeyRef:
        key: analytics
        name: egov-service-host
