# Common Labels
labels:
  app: "workbench-ui"
  group: "web"

namespace: egov    

# Ingress Configs
ingress:
  enabled: true
  context: "workbench-ui"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "pucarsolutionsdev.azurecr.io/workbench-ui"
  tag: main-be4dcf578fa5e69552537150cf52d3b2b1afc9af
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/workbench-ui/"
  readinessProbePath: "/workbench-ui/"

extraVolumes: |
  - name: js-injection
    configMap:
      name: workbench-ui-js-injection

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf