# Common Labels
labels:
  app: "transformer"
  group: "backend"

# Ingress Configs
ingress:
  zuul: true
  enabled: true
  context: "transformer"


# Init Containers Configs
healthChecks:
  enabled: true
  livenessProbePath: "/transformer/health"
  readinessProbePath: "/transformer/health"

# Container Configs
image:
  repository: "pucarsolutionsdev.azurecr.io/pucar_transformer"
  tag: v1.0.0-7471513f26785fb63b13c6d7ad1f47e1fb65ce77
  imagePullPolicy: Always
replicas: "1"
httpPort: 8080
appType: "java-spring"
heap: "-Xmx64m -Xms64m"
java-args: "-Dspring.profiles.active=monitoring"
memory_requests: 256Mi


env: |
  - name: MANAGEMENT_HEALTH_ELASTICSEARCH_ENABLED
    value: "false"
  - name: MANAGEMENT_HEALTH_REDIS_ENABLED
    value: "false"
  - name: JAVA_ENABLE_DEBUG
    value: "true"
  - name: JAVA_DEBUG_PORT
    value: "5005"
  - name: SERVER_PORT
    value: "8080"
  - name: SERVER_CONTEXT_PATH
    value: /transformer
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-url
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
  - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: kafka-brokers
  - name: STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id  
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user
  - name: TF_HRMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-hrms
  - name: EGOV_WF_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: EGOV_PGR_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: pgr-services
  - name: EGOV_CASE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: case
  - name: ELASTICSEARCH_SERVER_HOST
    valueFrom:
      configMapKeyRef:
        key: es-host
        name: egov-config
  - name: ELASTICSEARCH_USER_NAME
    valueFrom:
      secretKeyRef:
        name: elasticsearch-credentials
        key: username
  - name: ELASTICSEARCH_USER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-credentials
        key: password
  - name: ELASTICSEARCH_CONNECTION_TYPE
    value: http
  - name: egov.user.search.path
    value: /user/v1/_search
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: DRISTI_HEARING_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: hearing
  - name: EGOV_ADVOCATE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: advocate