# Common Labels
labels:
  app: "digit-ui"
  group: "web"

# Ingress Configs
ingress:
  enabled: true
  context: "ui"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "pucarsolutionsdev.azurecr.io/digit-ui"
  tag: v1.0.0-d6576c3d536fa779c0ec2e0341d788821550841f
replicas: "1"
httpPort: 80
healthChecks:
  enabled: true
  livenessProbePath: "/ui/"
  readinessProbePath: "/ui/"

env: |
  - name: REACT_APP_ESIGN_FILESTORE_ID
    valueFrom:
      configMapKeyRef:
        key: esign-filestore-id
        name: egov-config
  - name: REACT_APP_KIBANA_USERNAME
    valueFrom:
      secretKeyRef: 
        name: kibana
        key: username
  - name: REACT_APP_KIBANA_PASSWORD
    valueFrom:
      secretKeyRef: 
        name: kibana
        key: password
    
extraVolumes: |
  - name: js-injection
    configMap:
      name: digit-ui

extraVolumeMounts: |
  - mountPath: /etc/nginx/conf.d/sub_filter.conf
    name: js-injection
    subPath: sub_filter.conf
