templates:
  default: &default
    chart: ./charts/core-services/{{`{{ .Release.Name }}`}}
    version: 0.1.0
    namespace: egov
    # This prevents helmfile exiting when it encounters a missing file
    # Valid values are "Error", "Warn", "Info", "Debug". The default is "Error"
    # Use "Debug" to make missing files errors invisible at the default log level(--log-level=INFO)
    missingFileHandler: Warn
    values:
      - ./charts/environments/{{ requiredEnv "HELMFILE_ENV" }}-secrets.yaml
      - ./charts/environments/{{ requiredEnv "HELMFILE_ENV" }}.yaml
commonLabels:
  deployment: "pucar"

releases:
  - name: openapi # Replace with your desired namespace
    installed: true # Replace with the version of your chart, if needed
    <<: *default
  - name: task  # Replace with your desired namespace
    installed: true
    labels:
      deployment: "task"
    <<: *default
  - name: order-management # Replace with your desired namespace
    installed: true # Replace with the version of your chart, if needed
    <<: *default
  - name: transformer # Replace with your desired namespace
    installed: true
    labels:
      deployment: "transformer"
    <<: *default
  - name: hearing  # Replace with your desired namespace
    installed: true
    labels:
      deployment: "hearing"
    <<: *default
  - name: case  # Replace with your desired namespace
    installed: true
    labels:
      deployment: "case"
    <<: *default
  - name: digit-ui # Replace with your desired namespace
    installed: true
    <<: *default
  - name: scheduler # Replace with your desired namespace
    installed: true
    <<: *default
