# Common Labels
labels:
  app: "hearing-management"
  group: "backend"

# Ingress Configs
ingress:
  zuul: true
  enabled: true
  context: "hearing-management"


# Init Containers Configs


# Container Configs
image:
  repository: "pucarsolutionsdev.azurecr.io/hearing-management"
  tag: v1.0.0-78a6b1093a50e53a427de8e49b404f220d905739
  imagePullPolicy: Always
replicas: "1"
httpPort: 8080
appType: "java-spring"
java-args: "-Dspring.profiles.active=monitoring"
heap: "-Xmx256m -Xms256m -agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n"
debugPort: 8000
remote_debug:
  enabled: true
memory_limits: 640Mi
env: |
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: -Dspring.profiles.active=monitoring
  - name: SERVER_PORT
    value: "8080"
  - name: SERVER_CONTEXT_PATH
    value: /hearing-management
  - name: DRISTI_HEARING_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: hearing