# Common Labels
labels:
  app: "order-management"
  group: "backend"

# Ingress Configs
ingress:
  zuul: true
  enabled: true
  context: "order-management"

healthChecks:
  enabled: true
  livenessProbePath: "/order-management/health"
  readinessProbePath: "/order-management/health"


# Container Configs
image:
  repository: "pucarsolutionsdev.azurecr.io/order-management"
  tag: v1.0.0-78a6b1093a50e53a427de8e49b404f220d905739
  imagePullPolicy: Always
replicas: "1"
httpPort: 8080
appType: "java-spring"
java-args: "-Dspring.profiles.active=monitoring"
heap: "-Xmx256m -Xms256m -agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n"
debugPort: 8000
remote_debug:
  enabled: true
memory_limits: 640Mi
env: |
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: -Dspring.profiles.active=monitoring
  - name: SERVER_PORT
    value: "8080"
  - name: SERVER_CONTEXT_PATH
    value: /order-management
  - name: EGOV_IDGEN_PATH
    value: "egov-idgen/id/_generate"
  - name: EGOV_STATELEVEL_TENANTID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: DRISTI_INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        key: individual
        name: egov-service-host
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_LOCALIZATION_SEARCH_ENDPOINT
    value: /_search
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        key: kafka-brokers
        name: egov-config
  - name: EGOV_INDEXER_ES_HOST_NAME
    valueFrom:
      configMapKeyRef:
        key: es-host
        name: egov-config
  - name: EGOV_INFRA_INDEXER_HOST
    valueFrom:
      configMapKeyRef:
        key: es-indexer-host
        name: egov-config
  - name: DRISTI_ESIGN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: e-sign-svc
  - name: EGOV_INDEXER_ES_USERNAME
    valueFrom:
      secretKeyRef:
        name: elasticsearch-credentials
        key: username
  - name: EGOV_INDEXER_ES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-credentials
        key: password

  - name: DRISTI_FILESTORE_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-filestore
        name: egov-service-host
  - name: DRISTI_ORDER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: order
  - name: DRISTI_ADVOCATE_HOST
    valueFrom:
      configMapKeyRef:
        key: advocate
        name: egov-service-host
  - name: DRISTI_TASK_HOST
    valueFrom:
      configMapKeyRef:
        key: task
        name: egov-service-host
  - name: DRISTI_APPLICATION_HOST
    valueFrom:
      configMapKeyRef:
        key: application
        name: egov-service-host
  - name: DRISTI_CASE_HOST
    valueFrom:
      configMapKeyRef:
        key: case
        name: egov-service-host
  - name: DRISTI_HEARING_HOST
    valueFrom:
      configMapKeyRef:
        key: hearing
        name: egov-service-host
  - name: DRISTI_ADIARY_HOST
    valueFrom:
      configMapKeyRef:
        key: ab-diary
        name: egov-service-host
  - name: DRISTI_INBOX_HOST
    valueFrom:
      configMapKeyRef:
        key: inbox
        name: egov-service-host
  - name: DRISTI_ANALYTICS_HOST
    valueFrom:
        configMapKeyRef:
          key: analytics
          name: egov-service-host
  - name: DRISTI_SCHEDULER_HOST
    valueFrom:
        configMapKeyRef:
          key: scheduler
          name: egov-service-host
  - name: SPRING_REDIS_HOST
    value: redis.backbone
  - name: SPRING_REDIS_PORT
    value: "6379"
  - name: DRISTI_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: DRISTI_PAYMENT_CALCULATOR_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service