# Common Labels
labels:
  app: "etreasury"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "etreasury"

# Init Containers Configs
initContainers:
  dbMigration:
    enabled: true
    schemaTable: "public_treasury_schema"
    image:
      repository: "pucarsolutionsdev.azurecr.io/etreasury_db"
      tag: v1.0.0-99889cae2385df27aedce8b7d8a1d28d8ee14715

# Container Configs
image:
  repository: "pucarsolutionsdev.azurecr.io/etreasury"
  tag: v1.0.0-99889cae2385df27aedce8b7d8a1d28d8ee14715

#healthChecks:
#  enabled: true
#  livenessProbePath: "/etreasury/"
#  readinessProbePath: "/etreasury/"
replicas: "1"
appType: "java-spring"
tracing-enabled: true
java-args: ""
heap: "-Xmx192m -Xms192m -agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n"
debugPort: 8000
remote_debug:
  enabled: true
# Additional Container Envs
env: |
  - name: PUCAR_TSB_RECEIPT
    value: "Y"
  - name: TREASURY_HEAD_IDS
    value: 56685,55622,00027,00029
  - name: TREASURY_ACCOUNT_NUMBERS
    value: 8031-00-102-94-07-00-00-N-V,8031-00-102-94-03-00-00-N-V
  - name: OFFICE_CODE
    value: 030101B0019
  - name: TREASURY_ACCOUNT_TYPE
    value: 01,14
  - name: CHALLAN_TEST_AMOUNT
    value: "4"
  - name: ISTEST_ENABLED
    value: "true"
  - name: SERVER_PORT
    value: "8080"
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: EGOV_STATE_LEVEL_TENANT_ID
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: egov-state-level-tenant-id
  - name: SPRING_FLYWAY_URL
    valueFrom:
      configMapKeyRef:
        key: db-url
        name: egov-config
  - name: SPRING_FLYWAY_USER
    valueFrom:
      secretKeyRef:
        key: username
        name: db
  - name: SPRING_FLYWAY_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: db-url
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: db
        key: username
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db
        key: password
  - name: "SCHEMA_TABLE"
    value: "public_treasury_schema"
  - name: "SPRING_FLYWAY_TABLE"
    value: "public_treasury_schema"
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        key: kafka-brokers
        name: egov-config
  - name: EGOV_COLLECTIONSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        key: collection-services
        name: egov-service-host
  - name: EGOV_FILE_STORE_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-filestore
        name: egov-service-host
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-idgen
  - name: SERVICE_DEPT_CODE
    valueFrom:
      configMapKeyRef:
        name: egov-config
        key: service-dept-code
  - name: EGOV_PDF_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: pdf-service
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_PDF_SERVICE_CREATE_ENDPOINT
    value: pdf-service/v1/_createnosave
  - name: DRISTI_CASE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: case
  - name: EGOV_DEMAND_HOST
    valueFrom:
      configMapKeyRef:
        key: billing-service
        name: egov-service-host


