# Common Labels
labels:
  app: "openapi"
  group: "backend"

# Ingress Configs
ingress:
  enabled: true
  context: "openapi"



#healthChecks:
#  enabled: true
#  livenessProbePath: "/openapi/health"
#  readinessProbePath: "/openapi/health"

# Container Configs
image:
  repository: "pucarsolutionsdev.azurecr.io/pucar_openapi"
  tag: develop-64544fb50f20302915a9a766883b0106b1e9a8cf
  imagePullPolicy: Always
replicas: "1"
httpPort: 8080
appType: "java-spring"
java-args: "-Dspring.profiles.active=monitoring"
heap: "-Xmx256m -Xms256m -agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n"
debugPort: 8000
remote_debug:
  enabled: true
memory_limits: 640Mi
env: |
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: -Dspring.profiles.active=monitoring
  - name: SERVER_PORT
    value: "8080"
  - name: SERVER_CONTEXT_PATH
    value: /OpenAPI
  - name: EGOV_IDGEN_PATH
    value: "egov-idgen/id/_generate"
  - name: EGOV_WORKFLOW_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-workflow-v2
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_LOCALIZATION_SEARCH_ENDPOINT
    value: /_search
  - name: EGOV_INDIVIDUAL_HOST
    valueFrom:
      configMapKeyRef:
        key: individual
        name: egov-service-host
  - name: KAFKA_CONFIG_BOOTSTRAP_SERVER_CONFIG
    valueFrom:
      configMapKeyRef:
        key: kafka-brokers
        name: egov-config
  - name: HEARING_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        key: hearing
        name: egov-service-host
  - name: CASE_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: case
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-mdms-service
        name: egov-service-host
  - name: EGOV_IDGEN_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-idgen
        name: egov-service-host
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-user
        name: egov-service-host
  - name: EGOV_HRMS_HOST
    valueFrom:
      configMapKeyRef:
        key: egov-hrms
        name: egov-service-host
  - name: EGOV_URL_SHORTNER
    valueFrom:
      configMapKeyRef:
        key: egov-url-shortening
        name: egov-service-host
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: /egov-mdms-service/v1/_search
